### ISSUE TITLE
Compile error with kernel 3.16 on Ubuntu

### ISSUE THREAD

**Issue by daver1691** [simon3z/usbtv#6]
I'd previously compiled this module with no problems with kernel 3.13 on Ubuntu 14.04 but it failed to compile with kernel 3.16 on Ubuntu 14.10. The error message being "warning: initialization from incompatible pointer type". Any ideas, please?

```
$ make -C /lib/modules/$(uname -r)/build M=$PWD
make: Entering directory '/usr/src/linux-headers-3.16.0-24-generic'
  LD      /work/sys/drivers/usbtv-master/built-in.o
  CC [M]  /work/sys/drivers/usbtv-master/usbtv-core.o
  CC [M]  /work/sys/drivers/usbtv-master/usbtv-video.o
/work/sys/drivers/usbtv-master/usbtv-video.c:653:2: warning: initialization from incompatible pointer type
  .stop_streaming = usbtv_stop_streaming,
  ^
/work/sys/drivers/usbtv-master/usbtv-video.c:653:2: warning: (near initialization for ‘usbtv_vb2_ops.stop_streaming’)
/work/sys/drivers/usbtv-master/usbtv-video.c: In function ‘usbtv_video_init’:
/work/sys/drivers/usbtv-master/usbtv-video.c:683:13: error: ‘struct vb2_queue’ has no member named ‘timestamp_type’
  usbtv->vb2q.timestamp_type = V4L2_BUF_FLAG_TIMESTAMP_MONOTONIC;
             ^
scripts/Makefile.build:257: recipe for target '/work/sys/drivers/usbtv-master/usbtv-video.o' failed
make[1]: *** [/work/sys/drivers/usbtv-master/usbtv-video.o] Error 1
Makefile:1345: recipe for target '_module_/work/sys/drivers/usbtv-master' failed
make: *** [_module_/work/sys/drivers/usbtv-master] Error 2
make: Leaving directory '/usr/src/linux-headers-3.16.0-24-generic'
```

**Comment by kbal264** [comment]
Same here on OpenSuSE 13.2 (3.16.6-2-desktop).

**Comment by kbal264** [comment]
The latest kernel RC has audio support. The driver code compiles with 3.16, so you can just grab it from the kernel source and compile it yourself. The driver code is in drivers/media/usb/usbtv/

**Comment by UMLAUTaxl** [comment]
There is no usbtv-audio.c in kernel driver sources 3.16
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/drivers/media/usb/usbtv?h=v3.16
It's only available in 3.18 and higher.

**Comment by UMLAUTaxl** [comment]
When compiling 3.18 (with 3.16 kernel and sources) I get
    insmod: ERROR: could not insert module usbtv.ko: Unknown symbol in module

**Comment by simon3z** [comment]
@kbal264 @UMLAUTaxl IIRC this module was officially introduced into kernel 3.10.25 / 3.11

**Comment by UMLAUTaxl** [comment]
Thanks, simon3z. But usbtv-audio.c is only available from 3.18 and up. So there's no audio support below that.
I installed kernel 4.2 and now it works out of the box.
I'm on Debian Jessie and the kernel comes from the backports repositories (4.2.6-1~bpo8+1).
